services:
  - type: web
    name: custom-redis-server
    env: docker
    plan: standard  # free doesn't allow non-HTTP ports
    dockerfilePath: Dockerfile

    # EXPOSE NON-HTTP PORT
    ports:
      - port: 6379
        protocol: tcp
